version: '3.5'

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      SQLALCHEMY_DATABASE_URI: sqlite:////tmp/core.db
      CONFIG_NAME: Config
    volumes:
    - ./core:/app/core
    ports:
      - 5000:5000
    depends_on:
      - pg
  pg:
    image: postgres:12
    environment:
      POSTGRES_DB: core
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ${HOME}/dbs/flask-lesson/pgdata_dev:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432